### ISSUE TITLE
Style of figures is not consistent

### ISSUE THREAD

**Issue by AllenDowney** [AllenDowney/ThinkJava#12]
Most of the figures were done in xfig; a few were done in dia.  We are waiting for guidance about whether they will be redone in production, or whether we should make them consistent.

**Comment by DanGitOreilly** [comment]
Hi Allen. Our preference would be to redraw the art after production officially begins. We're not familiar with xfig or dia, but if you can supply PDF or some other vector format, our illustrator should be fine.

**Comment by AllenDowney** [comment]
That's fine.  The repo has the pdf versions of the figures and also the source files (xfig and dia).

The only issue we should figure out is what to do if we update a figure.  How do we let you know that we need an update?

**Comment by DanGitOreilly** [comment]
We don't do any work on figures until production officially begins, so you
can feel free to change figures up till then. If you need to change
something after production starts, you'd want to communicate that to the
production editor that will be working on your project.

Dan

**Comment by AllenDowney** [comment]
Ok, closing.
