### ISSUE TITLE
Exercises should be labeled as exercises, not examples

### ISSUE THREAD

**Issue by AllenDowney** [AllenDowney/ThinkJava#5]
This is a recurring issue.  It would be nice if we could add this feature to Atlas rather than fixing it by hand in all of my books.

**Comment by DanGitOreilly** [comment]
We implement this as a customization for your specific books, so we don't want to build it into Atlas. If you come to us when you create a new project, we'd be happy to configure it for you then, or we can continue to do so during production.

**Comment by kristenORM** [comment]
Allen, I believe this is all set (as seen in the CE PDF), but let me know if this issue is not resolved.

**Comment by AllenDowney** [comment]
All set!
