### ISSUE TITLE
Sizing information for figures is ignored

### ISSUE THREAD

**Issue by AllenDowney** [AllenDowney/ThinkJava#6]
Currently we have to scale the figures by hand in production.  It would be nice if Atlas would accept size information.

**Comment by DanGitOreilly** [comment]
At present, we ignore specific sizing instructions. Not at all ideal, I know. Instead, our illustrator and production editors work with the authors to address any specific sizing during production.

**Comment by kristenORM** [comment]
The QC1 PDF will have the final art in place, so you can let me know at that point if anything is sized incorrectly.

**Comment by AllenDowney** [comment]
Sounds good.

**Comment by AllenDowney** [comment]
Looks good!
