### ISSUE TITLE
Tables need lines

### ISSUE THREAD

**Issue by AllenDowney** [AllenDowney/ThinkJava#7]
We need lines between cells on all tables, especially the one that's a blank table for the reader to fill in (Exercise 9.1).  If there's a way to do this in DocBook, please let me know.

**Comment by DanGitOreilly** [comment]
I recommend you note this when you turn your book over to production and we'll address this in a oneoff for the CSS stylesheet that we use to generate the PDF and other formats.

**Comment by kristenORM** [comment]
Allen, the CE PDF showed lines on all tables, so I think this is resolved, but let me know if further tweaks are needed.

**Comment by AllenDowney** [comment]
All set!
