### ISSUE TITLE
Figure 10.1 is broken

### ISSUE THREAD

**Issue by AllenDowney** [AllenDowney/ThinkJava#8]
We don't know why.  This has been an intermittent issue for a while: it was broken, then it worked for a while, now it is broken again.

**Comment by ChrisMayfield** [comment]
Figure 15-1 is broken now too. I noticed there are some files in the images directory on Atlas that are also in the figs directory (and some are older versions). Could that be creating a conflict?

**Comment by DanGitOreilly** [comment]
If you remove the `<para>` tags from the `<figure>` markup, it should work. I tested on a branch and found it be be successful.

Here's the markup for Figure 10-1, including the errant `<para>`:

```
<figure id="fig.reference" float="False">
    <title>State diagram showing a variable that refers to a <literal remap="verb">Point object.</literal></title>


  <para> <mediaobject>
  <imageobject remap="includegraphics">
    <imagedata fileref="figs/reference.pdf"></imagedata>
  </imageobject>
</mediaobject></para>

  </figure>
```

**Comment by AllenDowney** [comment]
Resolved with a change in plastex's treecleaner.py
